### ISSUE TITLE
互不影响啥意思？

### ISSUE THREAD

**Issue by junmoxiao** [c0ny1/passive-scan-client#17]
“该插件正是为了解决该问题，将正常访问网站的流量与提交给被动扫描器的流量分开，互不影响。“

这流量还是本地发出去的吧，为啥不影响？

**Comment by ws4** [comment]
正常大家都是 `浏览器->burp->被动扫描器->服务器` 被动扫描会发出很大探测payload触发waf，这时候你正常的burp测试也会受到影响。同时这样也影响人工burp测试的网速。
