### ISSUE TITLE
可以考虑下添加一个关键字过滤功能

### ISSUE THREAD

**Issue by i11us0ry** [c0ny1/passive-scan-client#35]
可以考虑下添加一个关键字过滤功能
比如某个项目我希望含有delete的url不被扫描
某个项目希望含有remove的url不被扫描

**Comment by c0ny1** [comment]
这是个不错的需求。目前比较忙，可能需要过一段时间才支持。

**Comment by i11us0ry** [comment]
感谢回复，我已经改好了，还加了个手动右键发送功能，待会更新到项目上您有空看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 上午10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [c0ny1/passive-scan-client] 可以考虑下添加一个关键字过滤功能 (Issue #35)




 
这是个不错的需求。目前比较忙，可能需要过一段时间才支持。

**Comment by c0ny1** [comment]
没问题

**Comment by c0ny1** [comment]
已经合并 b1ef2a1e14983d06be75664367b68c0188b0fb17
