### ISSUE TITLE
 和xray配合使用的时候，基本请求都是502

### ISSUE THREAD

**Issue by haoirui** [c0ny1/passive-scan-client#4]
![ggggg](https://user-images.githubusercontent.com/8946580/63746709-09896080-c8d8-11e9-9b88-74dc6b574a96.png)

**Comment by ws4** [comment]
Fail:50,说明提交来51次，有50次失败了

**Comment by haoirui** [comment]
@ws4 这失败率有点高啊，不知道是哪方面的问题

**Comment by ws4** [comment]
502代表的应该是插件已决定代理到你指定的地址了，不然会提示无法链接的。应该是xray返回了状态码为502。我的一般感觉没啥事

![image](https://user-images.githubusercontent.com/27466935/63747539-fb3c4400-c8d9-11e9-8e0a-77ef5b0a7dcd.png)

**Comment by ws4** [comment]
@haoirui 编译最新源码试试

**Comment by haoirui** [comment]
@ws4 感谢

**Comment by Stowaway-y** [comment]
我的这个request界面什么都没有啊。这大概是什么问题
![123](https://user-images.githubusercontent.com/42023732/64072142-277e0900-ccbc-11e9-9459-51b16321b4cb.png)

**Comment by c0ny1** [comment]
你把分割面板控件往下拉，选中一条记录就会显示了
