### ISSUE TITLE
点击run后，无法转发流量

### ISSUE THREAD

**Issue by x24thkk** [c0ny1/passive-scan-client#40]
不点击run，使用右键点击发送到扩展可以使用，点击后右键发送也会失效

**Comment by x24thkk** [comment]
然后点击stop 停下来后，右键也会失效 ，这个是卡住了么

**Comment by x24thkk** [comment]
进入  HttpAndHttpsProxy.Proxy 后就不会动了 🥹

**Comment by LztCode** [comment]
看这个：https://github.com/c0ny1/passive-scan-client/pull/34
